# Generated by Django 3.2.8 on 2021-10-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211028_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
